### ISSUE TITLE
Hi, friend.

### ISSUE THREAD

**Issue by Open343** [visualcookie/slim-sentinel-auth#1]
hello！

Why is  not updated for three months?

And, can you provide a database .sql file? Thank you!

**Comment by visualcookie** [comment]
Hi @Open343,

sorry I've been busy working on other projects. I'll look into this project pretty soon, but I'll try to get an SQL file out today for you. :)

Hope you have some patience.

**Comment by Open343** [comment]
Hello, friends! Your next update can make some videos and upload to YouTube?Thank you!

**Comment by visualcookie** [comment]
Not sure, why it should do this. For a record: this is only a boilerplate for managing users and roles in a Slim 3 Application. What you develop out of it, is completely up to you.
